steps:
  # build the application
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/service-auth:latest", "."]
  # push the image to artifact registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/service-auth:latest"]
  # deploy the application in cloud run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "service-auth"
      - "--image"
      - "gcr.io/${PROJECT_ID}/service-auth:latest"
      - "--allow-unauthenticated"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--ingress"
      - "internal"
      - "--memory"
      - "512Mi"

timeout: 1200s
images: ["gcr.io/${PROJECT_ID}/service-auth:latest"]
